'use client'

export const dynamic = 'force-dynamic'

import { motion } from 'framer-motion'
import { Download, FileText, TrendingUp, BarChart3, Calendar } from 'lucide-react'
import { useState } from 'react'

export default function AccountingPage() {
  // Mock reports generated by INVITEFOCUS - will be replaced with real Supabase data
  const generatedReports = [
    {
      id: 1,
      name: 'États Financiers - Juin 2024',
      type: 'Monthly Report',
      date: '2024-06-30',
      generated: '2024-07-05',
      icon: BarChart3,
      status: 'completed',
    },
    {
      id: 2,
      name: 'Suivi Trésorerie - Juin 2024',
      type: 'Cash Flow',
      date: '2024-06-30',
      generated: '2024-07-05',
      icon: TrendingUp,
      status: 'completed',
    },
    {
      id: 3,
      name: 'Diagnostic Comptable - Q2 2024',
      type: 'Quarterly Diagnosis',
      date: '2024-06-30',
      generated: '2024-07-08',
      icon: FileText,
      status: 'completed',
    },
    {
      id: 4,
      name: 'États Financiers - Mai 2024',
      type: 'Monthly Report',
      date: '2024-05-31',
      generated: '2024-06-05',
      icon: BarChart3,
      status: 'completed',
    },
  ]

  const financialSummary = {
    revenue: '$24,500',
    revenueChange: '+12% MoM',
    expenses: '$8,200',
    expensesChange: '-3% vs budget',
    netProfit: '$16,300',
    netProfitChange: '+18% YoY',
  }

  return (
    <div className="p-6 lg:p-8">
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
        <h1 className="text-3xl font-bold text-[#0F172A] mb-2">◐ Assistance Comptable</h1>
        <p className="text-gray-600">
          Vos rapports financiers générés par INVITEFOCUS — États financiers, trésorerie, diagnostic
        </p>
      </motion.div>

      {/* Financial Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="grid lg:grid-cols-3 gap-6 mb-8"
      >
        {[
          { label: 'Revenus ce mois', value: financialSummary.revenue, change: financialSummary.revenueChange },
          { label: 'Dépenses', value: financialSummary.expenses, change: financialSummary.expensesChange },
          { label: 'Solde net', value: financialSummary.netProfit, change: financialSummary.netProfitChange },
        ].map((stat, idx) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 + idx * 0.1 }}
            className="bg-white rounded-lg border border-gray-200 p-6"
          >
            <p className="text-sm text-gray-600 font-medium mb-2">{stat.label}</p>
            <p className="text-3xl font-bold text-[#0F172A] mb-2">{stat.value}</p>
            <p className="text-sm text-green-600">{stat.change}</p>
          </motion.div>
        ))}
      </motion.div>

      {/* Generated Reports */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="mb-8"
      >
        <h2 className="text-xl font-bold text-[#0F172A] mb-6">Vos rapports générés ({generatedReports.length})</h2>
        <div className="space-y-3">
          {generatedReports.map((report, idx) => {
            const Icon = report.icon
            return (
              <motion.div
                key={report.id}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.2 + idx * 0.05 }}
                className="bg-gradient-to-r from-blue-50 to-blue-100 rounded-lg p-4 border border-blue-200 flex items-center justify-between group hover:shadow-md transition-all"
              >
                <div className="flex items-center gap-4 flex-1">
                  <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center flex-shrink-0">
                    <Icon size={20} className="text-[#2563EB]" />
                  </div>
                  <div className="flex-1">
                    <p className="font-semibold text-[#0F172A] text-sm">{report.name}</p>
                    <div className="flex items-center gap-4 mt-1 text-xs text-gray-600">
                      <span className="font-medium text-blue-700">{report.type}</span>
                      <span className="flex items-center gap-1">
                        <Calendar size={14} />
                        {report.date}
                      </span>
                      <span>Généré: {report.generated}</span>
                    </div>
                  </div>
                </div>
                <button className="px-4 py-2 bg-[#2563EB] text-white rounded-lg font-semibold text-sm opacity-0 group-hover:opacity-100 transition-opacity hover:bg-[#1D4ED8] flex items-center gap-2">
                  <Download size={16} />
                  Télécharger
                </button>
              </motion.div>
            )
          })}
        </div>
      </motion.div>

      {/* Ratios & Indicators */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
        className="bg-white rounded-lg border border-gray-200 p-6"
      >
        <h3 className="text-lg font-bold text-[#0F172A] mb-6">Indicateurs clés</h3>
        <div className="grid md:grid-cols-4 gap-4">
          {[
            { label: 'Marge brute', value: '68%', color: 'text-green-600' },
            { label: 'Ratio trésorier', value: '2.1x', color: 'text-blue-600' },
            { label: 'Délai de paiement', value: '32 jours', color: 'text-amber-600' },
            { label: 'Burn rate', value: '0.23x revenue', color: 'text-red-600' },
          ].map((metric) => (
            <div key={metric.label} className="p-4 bg-[#FAFAFA] rounded-lg border border-gray-200">
              <p className="text-xs text-gray-500 font-semibold mb-2">{metric.label}</p>
              <p className={`text-2xl font-bold ${metric.color}`}>{metric.value}</p>
            </div>
          ))}
        </div>
      </motion.div>

      {/* Info Box */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-4"
      >
        <p className="text-sm text-blue-700">
          <span className="font-semibold">💡 Info:</span> Ces rapports ont été générés par nos experts après audit
          complet de vos documents. Vous avez accès à l'intégralité de vos données mensuelles, avec analyses de
          trésorerie et recommandations.
        </p>
      </motion.div>
    </div>
  )
}
